/***************************************************************************************
* \file GPIO_control_U55_WWmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef GPIO_CONTROL_U55_WWMODEL_H
#define GPIO_CONTROL_U55_WWMODEL_H

extern const char GPIO_control_WWmodeldata[];
#define GPIO_CONTROL_WWMODELDATA_SIZE 7404

#endif // GPIO_CONTROL_U55_WWMODEL_H
