/***************************************************************************************
* \file GPIO_control_U55_CMDmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef GPIO_CONTROL_U55_CMDMODEL_H
#define GPIO_CONTROL_U55_CMDMODEL_H

extern const char GPIO_control_CMDmodeldata[];
#define GPIO_CONTROL_CMDMODELDATA_SIZE 1380

#endif // GPIO_CONTROL_U55_CMDMODEL_H
