/***************************************************************************************
* \file GPIO_control.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef GPIO_CONTROL_H
#define GPIO_CONTROL_H

#include <stdint.h>

#define GPIO_CONTROL_NUM_INTENTS 3
#define GPIO_CONTROL_NUM_COMMANDS 3
#define GPIO_CONTROL_NUM_VARIABLES 0
#define GPIO_CONTROL_NUM_VARIABLE_PHRASES 0
#define GPIO_CONTROL_NUM_UNIT_PHRASES 16
#define GPIO_CONTROL_INTENT_MAP_ARRAY_TOTAL_SIZE 6
#define GPIO_CONTROL_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE 3

extern const char* GPIO_control_intent_name_list[GPIO_CONTROL_NUM_INTENTS];

extern const char* GPIO_control_variable_name_list[GPIO_CONTROL_NUM_VARIABLES];

extern const char* GPIO_control_variable_phrase_list[GPIO_CONTROL_NUM_VARIABLE_PHRASES];

extern const char* GPIO_control_unit_phrase_list[GPIO_CONTROL_NUM_UNIT_PHRASES];

extern const int GPIO_control_intent_map_array[GPIO_CONTROL_INTENT_MAP_ARRAY_TOTAL_SIZE];

extern const int GPIO_control_intent_map_array_sizes[GPIO_CONTROL_NUM_COMMANDS];

extern const int GPIO_control_variable_phrase_sizes[GPIO_CONTROL_NUM_VARIABLES];

extern const int GPIO_control_unit_phrase_map_array[GPIO_CONTROL_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE];

extern const int GPIO_control_unit_phrase_map_array_sizes[GPIO_CONTROL_NUM_COMMANDS];

#endif // GPIO_CONTROL_H
