/***************************************************************************************
* \file test_gpio_control.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef TEST_GPIO_CONTROL_H
#define TEST_GPIO_CONTROL_H

#include <stdint.h>

#define TEST_GPIO_CONTROL_NUM_INTENTS 2
#define TEST_GPIO_CONTROL_NUM_COMMANDS 2
#define TEST_GPIO_CONTROL_NUM_VARIABLES 0
#define TEST_GPIO_CONTROL_NUM_VARIABLE_PHRASES 0
#define TEST_GPIO_CONTROL_NUM_UNIT_PHRASES 16
#define TEST_GPIO_CONTROL_INTENT_MAP_ARRAY_TOTAL_SIZE 4
#define TEST_GPIO_CONTROL_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE 2

extern const char* test_gpio_control_intent_name_list[TEST_GPIO_CONTROL_NUM_INTENTS];

extern const char* test_gpio_control_variable_name_list[TEST_GPIO_CONTROL_NUM_VARIABLES];

extern const char* test_gpio_control_variable_phrase_list[TEST_GPIO_CONTROL_NUM_VARIABLE_PHRASES];

extern const char* test_gpio_control_unit_phrase_list[TEST_GPIO_CONTROL_NUM_UNIT_PHRASES];

extern const int test_gpio_control_intent_map_array[TEST_GPIO_CONTROL_INTENT_MAP_ARRAY_TOTAL_SIZE];

extern const int test_gpio_control_intent_map_array_sizes[TEST_GPIO_CONTROL_NUM_COMMANDS];

extern const int test_gpio_control_variable_phrase_sizes[TEST_GPIO_CONTROL_NUM_VARIABLES];

extern const int test_gpio_control_unit_phrase_map_array[TEST_GPIO_CONTROL_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE];

extern const int test_gpio_control_unit_phrase_map_array_sizes[TEST_GPIO_CONTROL_NUM_COMMANDS];

#endif // TEST_GPIO_CONTROL_H
