/***************************************************************************************
* \file test_gpio_control_U55_CMDmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef TEST_GPIO_CONTROL_U55_CMDMODEL_H
#define TEST_GPIO_CONTROL_U55_CMDMODEL_H

extern const char test_gpio_control_CMDmodeldata[];
#define TEST_GPIO_CONTROL_CMDMODELDATA_SIZE 972

#endif // TEST_GPIO_CONTROL_U55_CMDMODEL_H
